### ISSUE TITLE
How to pass DeployOptions, like `autoUpdatePackage`?

### ISSUE THREAD

**Issue by chexxor** [neowit/tooling-force.com#11]
I want to use the "autoUpdatePackage" option, which is used in other SFDC deploy tools, like Ant Migration tool and JSForce, to be more forgiving of the contents of my source directory and my package.xml file.

The "deployOptions" in `conn.deploy(zipFile, deployOptions)` in [Session.scala#L771](https://github.com/neowit/tooling-force.com/blob/37e7369ec7ab4a743d473d4a023e44693d07cb2c/src/main/scala/com/neowit/apex/Session.scala#L771) -- is this the same options as the Metadata API's [deploy() DeployOptions](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy.htm#deploy_options)? If so, we can add some code to [Deploy.scala#L257](https://github.com/neowit/tooling-force.com/blob/0b50ee90133cea81ab16627c81c50e9289bc5efa/src/main/scala/com/neowit/apex/actions/Deploy.scala#L257) to pass these options.

It would be nice to set those options from the command line, which would allow vim-force.com plugin to store those config options in Vimscript variables.

**Comment by neowit** [comment]
Yes, the lines of code you specified do indeed work with Metadata DeployOptions.

Do you have a scenario where you think adding extra deploy options via command line would be beneficial?

If you want to set extra DeployOptions via command line then I assume you want same options applied to every deployment? Sounds a bit limiting and not very safe, in case of "autoUpdatePackage" and deployment to Prod.

**Comment by chexxor** [comment]
The use-case I have is -- My employer's SFDC project is currently deployed via Ant Migration Tool or the MavansMate deploy tool. I tried fully-deploying using tooling-force.com, but it failed due to having "object" files in the "src" directory having fields not defined in the package.xml file.

This was a little strange - how was MavensMate full deploy successful if tooling-force.com is *not*? I looked into the MM source code and I found it (might be) using the JSForce library to deploy, which uses the Metadata SOAP API and *might* have default values for the "autoUpdatePackage" and "allowMissingFiles" options. (I can't see where those options are set, so I can't be sure they are the difference.)

So yeah, you're right, these deploy options don't necessarily have to be passed via command line options, but it sounds like a reasonable parameter to have. I might *want* to toggle these options back and forth for different deploys, but I can't think of a practical case in which I *must*.

**Comment by neowit** [comment]
Thank you for the explanation.
I think by blindly allowing deployment tool to pickup everything in `src` folder you are heading down a dangerous path. In a "continuous deployment" type situation - package.xml must be carefully prepared and reject any garbage which might have made its way into `src` folder by some accident.

Now that you have been warned - I have created a test version of .jar file ([download here](https://www.dropbox.com/s/p6qrj85yxrw8rtd/tooling-force.com-0.3.4.3-%2311.jar?dl=1)) and using this one you can set deploy options in one of following ways:

1) via `g:apex_tooling_force_dot_com_java_params` variable in .vimrc
e.g.
    `let g:apex_tooling_force_dot_com_java_params = "-DdeployOptions.autoUpdatePackage=true"`

2) in config.properties file 

```
# Specify the login credentials for the desired Salesforce organization
sf.username = ...
sf.password = ...

sf.serverurl = https://test.salesforce.com

#metadata deploy options
deployOptions.autoUpdatePackage = false
```
3) via command line param, if you are running tooling-force.com.jar from command line and not using `server` mode

`... --deployOptions.autoUpdatePackage=true`



note 1: some parameters like `checkOnly` or which tests to run are already handled in a different way so those deployOptions.xxx will be ignored.

note 2: if you are running tooling-force.com.jar in `server` mode then bear in mind that configuration is loaded once on first access. i.e. if you start the server with `deployOptions.autoUpdatePackage=true` and then change to `deployOptions.autoUpdatePackage=false` then this config will not be picked up until you shutdown the server (kill java process).

Make sure to check `:ApexToolingVersion` to make sure you are using the right .jar. Version must report `0.3.4.3-#11`

**Comment by chexxor** [comment]
Three ways to specify deployOptions! Sick!

I downloaded the new jar and tried it out. The "not specified in package.xml" errors are gone, but I've still got errors to investigate. Stuff, like "Unknown type name 'CompanySettings' specified in package.xml" and "Cannot modify managed object". This leads me to believe that your deploymentOptions implementation works well.

Looks like your branch isn't uploaded to this repo, so I can't see for myself - is it designed such that I can also specify other deployOptions, like "allowMissingFiles"?

**Comment by neowit** [comment]
You can specify following deployment options:
- allowMissingFiles
- autoUpdatePackage
- checkOnly - note: if used with vim plugin then this one may be overridden by `:ApexDeploy...` and `:ApexSave` plugin commands
- ignoreWarnings
- performRetrieve
- purgeOnDelete
- rollbackOnError

**Comment by chexxor** [comment]
So, here's what I discovered - Our org's metadata files is stored in a git repo. We use an internal tool to deploy it via the metadata api. I learned yesterday that other tools won't directly work because our internal tool does has some custom logic to exclude a set of metadata files from the deploy by parsing that set of file names from a "exclude-components.yml" file.

Does adding this kind of feature sound out-of-bounds for this project? It sounds like a pretty useful thing. Specifying every single item in the package.xml file is not easy to maintain. I've done it in the past, but it's pretty awful when working with several developers who are constantly adding new files.

**Comment by neowit** [comment]
Dev. process you described sounds ... unorthodox. I would consider fixing the process instead of adding crutches like this "exclude" file you have.
"redundant" files is likely not the only problem which current process causes.

Having said that I do agree that something like simplified version of [.gitignore](http://git-scm.com/docs/gitignore) but for apex files may be useful. If you want to pursue this further please open another issue.

**Comment by neowit** [comment]
DeployOptions update (as of 01 September) is now merged into master.
Closing this issue for now.

If you still want "exclude" function please open another issue.
Thanks.
