### ISSUE TITLE
Failed to create Metadata Container. duplicate value found

### ISSUE THREAD

**Issue by chexxor** [neowit/tooling-force.com#15]
I'm getting the following error when using the ApexSaveOne command from "vim-force.com".

```
Awaiting connection...
Client connected from /127.0.0.1:52707
received command:  --action=saveSpecificFiles --tempFolderPath='/Users/aberg/Temp/vim-forcecom' --config='/Users/aberg/Temp/vim-forcecom/project.properties' --projectPath='/Users/aberg/workspace/sfdc/project' --ignoreConflicts=true --specificFiles='/var/folders/z6/g21f7bkd5sq9_m0sq9zvd3080000gn/T/vPgffQv/3-fileList.txt' --responseFilePath='/Users/aberg/workspace/sfdc/project/.vim-force.com/response_saveSpecificFiles' --pollWaitMillis=1000 --maxPollRequests=1000
[ERROR] Executor - java.lang.IllegalStateException: Failed to create Metadata Container. duplicate value found: Name duplicates value on record with id: 1dc540000008otW
[ERROR] Executor - [Ljava.lang.StackTraceElement;@726a8e0djava.lang.IllegalStateException: Failed to create Metadata Container. duplicate value found: Name duplicates value on record with id: 1dc540000008otW

[Ljava.lang.StackTraceElement;@4cabb279
RESULT=FAILURE
ERROR: {"text":"Failed to create Metadata Container. duplicate value found: Name duplicates value on record with id: 1dc540000008otW"}
Disconnect /127.0.0.1:52707

Press ENTER or type command to continue
```

I notice that the "1dc540000008otW" Id is the same every time I run this command.

Looks like the metadata container should be deleted on error in the [SaveModified class](https://github.com/neowit/tooling-force.com/blob/6530770d6b29c137a01f0501a0d1ee13d938ef76/src/main/scala/com/neowit/apex/actions/tooling/SaveModified.scala#L36).

I see a logger there, `logger.debug("Deleted MetadataContainer; Id=" + container.getId)`, but I'm not seeing this line in the command's output in the terminal. I spent time looking to see ways to configure the logger, but I can't figure it out.

Any tips? I'm using the latest release of tooling-force.com, btw, tooling-force.com-0.3.6.1.jar.

**Comment by neowit** [comment]
I think what you are observing is caused by broken `session.properties`.
My guess is that yours contains Id of metadata container which no longer exists in SFDC.

Please try [this](https://www.dropbox.com/s/mzuan4z2eyj1wl5/tooling-force.com-0.3.6.2.jar?dl=1) version.

**Comment by chexxor** [comment]
I opening the `session.properties` file but didn't see that Id, nor any references to metadata container. I downloaded the updated version, set vim-force.com to use it, and I've successful deployed using the Tooling API. So, your fix worked!

Much appreciated!

**Comment by liron50** [comment]
Late, but I had similar issue. 
Created MetadataContainer, add members and deploy it. It seems that if the deployment is failing, the error return when trying to create new MetadataContainer. 
I resolve it by deleting the previous that was failing 
sending http DELETE to /services/data/v43.0/tooling/sobjects/MetadataContainer/{duplicateId}/

**Comment by neowit** [comment]
Hello @liron50 
Thanks for your comment.
Indeed - back in 2016 I had to resort to the same method - [delete MetadataContainer "Duplicate Container" on error](https://github.com/neowit/tooling-force.com/commit/ccf4e2454e4c3b9254f5b30d1402926bb78392b3#diff-5bfc5609d5a91105431a1a4d0e6a5274R109)
