### ISSUE TITLE
No documentation for server-mode

### ISSUE THREAD

**Issue by colin-j** [neowit/tooling-force.com#16]
In README.md, it says to read :help server-mode in vim-force.com documentation carefully.  I do not see server-mode documented anywhere.

**Comment by neowit** [comment]
Hello @colin-j,

I am going to assume that you refer to `vim-force.com` README (even though you posted the issue in `tooling-force.com` project).  

`vim-force.com` no longer uses 2 modes of operation and does not require user to chose which mode to use.  
In case you are curious what that was about - take a look at [this](https://github.com/neowit/vim-force.com/blob/legacy-vim-sync/doc/force.com.txt#L1148).

If you are planning to use `tooling-force.com.jar` standalone (e.g. in CI setup) then you are most likely do not need a "server" mode.  

If you do still want to use a server mode then there is not much to it. You just start a server, e.g. 
```
 java -jar tooling-force.com.jar --action=serverStart --port=8888 --timeoutMillis=30000
```
and then send it commands like so:  
```
echo "--action=version --responseFilePath='~/temp/test-response.txt'" | nc localhost 8888
```

Let me know what you are trying to achieve with `tooling-force.com`, perhaps I may be able to advise how best do that.

**Comment by colin-j** [comment]
Thanks so my for your quick response.  I am sorry for opening this issue in the wrong project.  I was looking at both simultaneously.  Your explanation is good, and no I know that server-mode is no longer a separate mode of operation for vim-force.com.  I would suggest updating the README for that project, but there should be no issue for this project.

**Comment by neowit** [comment]
> I would suggest updating the README for that project

Good point, I now see that "server" reference in `vim-force.com` README may be confusing. Will remove it. Thank you for pointing out.
