### ISSUE TITLE
Optional auto-complete interface to allow input & output as string

### ISSUE THREAD

**Issue by ChuckJonas** [neowit/tooling-force.com#19]
I'm writing a vs-code plugin to leverage the auto-complete functionality.  I've got it working, but I'm having to write my input file (exists as an in memory buffer) and read the output.json.  

This is likely adding additional latency to the auto-completion, which should be as low as possible for the best user experience. 

I would be nice if I could just pass the `currentFileContent` as a string parameter and have the response instead written to standard out.

PS: great work on this! Even with a little latency the auto-complete seems to work very well.

**Comment by neowit** [comment]
Hello @ChuckJonas 

Writing a single (apex class size) file and reading small json data is probably taking milliseconds and is unlikely to be noticeable by the end user.
My [vim plugin](https://github.com/neowit/vim-force.com) does exact same thing, and the time to write buffer content to a file and then read response from another file is negligible compared to the time it takes to do the rest of the completion operation.

> I would be nice if I could just pass the currentFileContent as a string parameter

Passing the whole file content as a string parameter probably will have more disadvantages than advantages. Like string may be too long, escaping quotes, line feeds, etc. 

> have the response instead written to standard out.

You are not the first person making "respond to STDOUT" suggestion, so I actually considered it at one point, but then came across ["Language Server Protocol"](https://github.com/Microsoft/language-server-protocol/blob/master/README.md) and I like this one better. No concrete plans of implementing it though.

**Comment by ChuckJonas** [comment]
ok, I'll take your word about the reading and writing!

So your library is implementing the "Language Server Protocol"?  That's exactly what I'm trying to implement in vscode!  

Are things like "Go To Definition" or "Get Symbol" possible with your tool?

**Comment by neowit** [comment]
> So your library is implementing the "Language Server Protocol"? 

This is actually not what I meant in my last message. I like the idea of "Language Server Protocol" better than what `tooling-force.com.jar` provides, but presently have no concrete plans of implementing it. Besides, my main target `vim` does not support "Language Server Protocol".

**Comment by neowit** [comment]
> Are things like "Go To Definition" or "Get Symbol" possible with your tool?

Not at the moment because usually this can be achieved via other means. For example in `vim` it is done using `ctags`.

Current `tooling-force.com.jar` implementation (internally) already does 80% of what would be necessary for "Go To Definition" or "Get Symbol" because code completion needs to "know" symbol definition and type. But in order to expose real "Go To Definition" and "Get Symbol" some extra work is required.

**Comment by ChuckJonas** [comment]
At some point I might try to port your apex parsing and auto-complete stuff out to a stand-alone node library, if that is ok with you.
