### ISSUE TITLE
Porting grammar to Typescript

### ISSUE THREAD

**Issue by ChuckJonas** [neowit/tooling-force.com#26]
Hey, this isn't really an issue but I'm not sure how else to reach you.

I'm trying to port the [apexcode.g4](https://github.com/neowit/tooling-force.com/blob/master/src/main/java/Apexcode.g4#L1086) grammar to typescript.  I've pretty much got it to work but I'm running into a little bit of a snag in that I'm not sure how I should update some of the native java code references in the .g4 file:

```g4
fragment
JavaLetter
    :   [a-zA-Z$_] // these are the "java letters" below 0xFF
    |   // covers all characters above 0xFF which are not a surrogate
        ~[\u0000-\u00FF\uD800-\uDBFF]
        {Character.isJavaIdentifierStart(_input.LA(-1))}?
    |   // covers UTF-16 surrogate pairs encodings for U+10000 to U+10FFFF
        [\uD800-\uDBFF] [\uDC00-\uDFFF]
        {Character.isJavaIdentifierStart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)))}?
    ;

fragment
JavaLetterOrDigit
    :   [a-zA-Z0-9$_] // these are the "java letters or digits" below 0xFF
    |   // covers all characters above 0xFF which are not a surrogate
        ~[\u0000-\u00FF\uD800-\uDBFF]
        {Character.isJavaIdentifierPart(_input.LA(-1))}?
    |   // covers UTF-16 surrogate pairs encodings for U+10000 to U+10FFFF
        [\uD800-\uDBFF] [\uDC00-\uDFFF]
        {Character.isJavaIdentifierPart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)))}?
    ;
```

For example, I need to rewrite this line in javascript: `{Character.isJavaIdentifierPart(Character.toCodePoint((char)_input.LA(-2), (char)_input.LA(-1)))}`

I can get closer:

`{Character.isJavaIdentifierStart(Character.toCodePoint(this._input.LA(-2), this._input.LA(-1)))}`

but obviously the `Character` class isn't part of javascript so those don't compile.

Any help or direction on how I could go about porting these would be greatly appreciated.  Or if you could just help me understand what exactly the purpose of these lines are maybe I could take it from there.

Thanks

**Comment by neowit** [comment]
Hello @ChuckJonas 

`Character` is a standard java class. See doc [here](https://docs.oracle.com/javase/6/docs/api/java/lang/Character.html).

[Character.isJavaIdentifierStart](https://docs.oracle.com/javase/6/docs/api/java/lang/Character.html#isJavaIdentifierStart(int))

The purpose of these code snippets is to determine if current token contains a sequence of characters making it a valid letter or digit recognised by the language. For example
```
String myvar = 10;
```
here Lexer would check if `String`, `myvar` and `10` are valid things to stand on their own.   

I do not think apex supports unicode identifiers so you could just as well drop these.

**Comment by ChuckJonas** [comment]
I was hoping you'd say that...

Ya I looked into trying to port the `Character.isJavaIdentifierStart` over to javascript (or write the equivalent functionality) but it seemed like a lot of work.

I'm still learning ANTLR grammar syntax but I assume the grammar "sans unicode" would look something like this?

```
fragment
JavaLetter
    :   [a-zA-Z$_] // these are the "java letters" below 0xFF
    ;

fragment
JavaLetterOrDigit
    :   [a-zA-Z0-9$_] // these are the "java letters or digits" below 0xFF
    ;
```

**Comment by neowit** [comment]
Looks reasonable, except that I do not think apex supports `$` as part of an identifier either.

Out of interest - when you say you are porting this to TypeScript how exactly do you do that ?
Do you generate ANTLR output out of `.g4` file using target `javascript` ?

**Comment by ChuckJonas** [comment]
Ya, using [antlr4ts](https://github.com/tunnelvisionlabs/antlr4ts).  Super easy to get up an running.  Not sure what the performance will be like compared to java.

Right now hoping to just supplement your library. Adding javadoc style comment generation,  listing symbols (similar to #24), helping with function params, etc.

Long term I'd love to try and start implementing a Language Server Protocol, but really have no idea what would be involved in that yet.

**Comment by neowit** [comment]
In that case you may want to wait a little.

You may have noticed that I have not done much updating to tooling-force.com project lately.
Java based Apexcode.g4 grammar has served its purpose, but ultimately it is a dead end. It has too many issues. For instance - valid apex file may fail syntax check and thus everything else (e.g. completion) fails on such file either.

I have started another project (not yet available on Github) where Apex grammar is written from scratch and supports all sorts of peculiarities of apex which are not compatible with java.
In its current version I am yet to find an apex file which fails syntax check (which is easy with Apexcode.g4 you are using).

One noteworthy caveat - new project (and .g4 grammar) will most likely be released under [AGPL v3](https://www.gnu.org/licenses/agpl-3.0.en.html).

**Comment by neowit** [comment]
Forgot to mention - I have no plans abandoning tooling-force.com. I just want to extract apex analysis stuff into a separate library which tooling-force.com.jar will be using instead of current [java grammar](https://github.com/neowit/tooling-force.com/blob/master/src/main/java/Apexcode.g4) based implementation. From tooling-force.com.jar user's point of view not much will change (apart from improvements in apex analysis part).

**Comment by ChuckJonas** [comment]
that's awesome to hear.   Definitely look forward to seeing it.  Maybe by then, I'll be up to speed with ANTLR and can actually help contribute (although I'd also need to pick up scala). 

I have no problems with that licensing (at least according to [this](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)) summary).    To be honest, while I've tried to credit you at every chance, I'm not even sure if my use of tooling-force is within the bounds of your current license.

**Comment by ChuckJonas** [comment]
@neowit any idea on when you think you'll release the new grammar?  I broke ground on the typescript parser today.  

Also, will most the rules be the same? or is this a ground up rewrite?

**Comment by neowit** [comment]
New grammar is written from scratch, but as with any other "c" like syntax grammar it is inevitable that there are some parts which may look similar.

I am not ready to release the new project yet, as it is not in a usable shape, but I can share new grammar file if you want. No idea when it may get to release state. It is a spare time / hobby project after all.

In its present state the grammar is passing syntax check of all apex class/trigger files I have access to.
I can make no promises regarding how much the grammar file will change in the future though.

Let me know if you want me to share the .g4 file in its current state anyway.

**Comment by ChuckJonas** [comment]
@neowit that would be awesome and much appreciated!  If I find or fix any bugs I will make sure to share it with you.  And of course give you proper credit & follow licensing restrictions.

My email is chagonkas(at)gmail.com if you'd prefer to email it over.
