### ISSUE TITLE
Retrieving FieldSets

### ISSUE THREAD

**Issue by noenthu** [neowit/tooling-force.com#27]
Is it possible to retrieve Fieldsets using tooling-force?
When I retrieve a managed package object which has fieldsets and validation rules, it does not retrieve any associated fieldsets in the xml.

**Comment by neowit** [comment]
> Is it possible to retrieve Fieldsets using tooling-force?

Yes.


`bulkRetrieve` action should retrieve all parts of specified custom object(s), nothing special is needed to retrieve FieldSets.

example command
```
--action=bulkRetrieve --tempFolderPath='/temp' --authConfigPath='/some/path' --projectPath='/path/to/project' --debuggingHeaderConfig='/var/folders/1l/1096-apexTraceFlag.conf' --typesFileFormat=json --updateSessionDataOnSuccess=true --specificTypes='/path/to/file-with-types' --responseFilePath='/temp/response_bulkRetrieve' --pollWaitMillis=1000 --maxPollRequests=1000
```
example content of `file-with-types` referenced above
```json
{"XMLName": "CustomObject", "members": ["SomeNamespace_Custom_Object_Name__c"]}
```

FieldSets (if present) will be part of retrieved `SomeNamespace_Custom_Object_Name__c.object` file.

**Comment by noenthu** [comment]
Great - just tried and it worked. Thanks
