### ISSUE TITLE
Parser blows up if method names match system types

### ISSUE THREAD

**Issue by jamessimone** [neowit/tooling-force.com#28]
We had a class, SystemClock.cls, which had a method in it called "set" - the full stacktrace is below.  I have "resolved" the issue by renaming the method and all references to it for now.  I haven't had the full chance to look through your codebase yet, but in the event you get to it before me:

[INFO] SourceScanner - scanning file: SystemClock.cls

failed to add member of parent: SystemClock

[Ljava.lang.StackTraceElement;@741503f6
[ERROR] Executor - java.lang.NullPointerException
[ERROR] Executor - 	at com.neowit.apex.parser.ClassMethodMember.getMethodName(Member.scala:1146)
[ERROR] Executor - 	at com.neowit.apex.parser.ClassLikeMember.addChild(Member.scala:452)
[ERROR] Executor - 	at com.neowit.apex.parser.ApexTreeListener.registerMember(ApexTreeListener.scala:55)
[ERROR] Executor - 	at com.neowit.apex.parser.ApexTreeListener.enterClassBodyDeclaration(ApexTreeListener.scala:125)
[ERROR] Executor - 	at com.neowit.apex.parser.antlr.ApexcodeParser$ClassBodyDeclarationContext.enterRule(ApexcodeParser.java:1633)

**Comment by neowit** [comment]
Thank you for reporting this.

`set` is a Reserved Keyword: 
https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_reserved_words.htm?search_text=reserved%20keywords

if salesforce for some reason allowed you to use a reserved keyword for custom method name previously this does not mean that it will be as forgiving in the future. These keywords are listed as reserved for a reason.

Anyway - I have updated the completion code to not fail with NPE in such case. But completion will not include such method on the list. The effort to include it is not worth it.
This update will be part of next `tooling-force.com.jar` version.

**Comment by jamessimone** [comment]
Thank you for the extremely quick response!
