### ISSUE TITLE
listcompletions - NullpointerException

### ISSUE THREAD

**Issue by sankaran1984** [neowit/tooling-force.com#5]
Hi Andrey, 

i have just started using your vim-force.com plugin, Its awesome. I'm playing with all commands & getting myself familiar.
now, plugin is running in server mode.. i;m trying auto-complete in a apex file. i received null pointer exception in server console.  jre version -  1.8.0_25   tooling-force.com version - 0.3.1.4

Client connected from /127.0.0.1:60696
received command:  --action=listCompletions --tempFolderPath="C:\Users\\deiva\\v
im\\libraries\\force.com\\tmp" --config="C:\Users\\deiva\\vim\\libraries\\force.
com\\properties\at_dev.properties" --projectPath="C:\MyWs\at_dev" --logLevel=Det
ail --column=16 --line=26 --currentFilePath="C:\MyWs\at_dev\src\classes\AccountC
hildDealerContactsController.cls" --currentFileContentPath="C:\Users\deiva\AppDa
ta\Local\Temp\VIDD67C.tmpAccountChildDealerContactsController.cls" --responseFil
ePath="C:\MyWs\at_dev\.vim-force.com\response_listCompletions" --pollWaitMillis=
1000 --maxPollRequests=1000
java.lang.NullPointerException
com.neowit.apex.parser.PropertyMember$$anonfun$getModifiers$1.apply(Member.scala
:812)
com.neowit.apex.parser.PropertyMember$$anonfun$getModifiers$1.apply(Member.scala
:812)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)

scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)

scala.collection.Iterator$class.foreach(Iterator.scala:727)
scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
scala.collection.AbstractIterable.foreach(Iterable.scala:54)
scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
scala.collection.AbstractTraversable.map(Traversable.scala:105)
com.neowit.apex.parser.PropertyMember$.getModifiers(Member.scala:812)
com.neowit.apex.parser.PropertyMember.getModifiers(Member.scala:841)
com.neowit.apex.parser.PropertyMember.<init>(Member.scala:844)
com.neowit.apex.parser.TreeListener.enterPropertyDeclaration(TreeListener.scala:
94)
com.neowit.apex.parser.antlr.ApexcodeParser$PropertyDeclarationContext.enterRule
(ApexcodeParser.java:1960)
org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:66)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:49)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
com.neowit.apex.parser.SourceScanner$$anonfun$scan$1.apply(SourceScanner.scala:3
9)
com.neowit.apex.parser.SourceScanner$$anonfun$scan$1.apply(SourceScanner.scala:2
3)
scala.collection.immutable.List.foreach(List.scala:318)
com.neowit.apex.parser.SourceScanner.scan(SourceScanner.scala:23)
com.neowit.apex.actions.ScanSource.scan(ScanSource.scala:38)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1$$anonfun
$apply$2.apply(ListCompletions.scala:24)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1$$anonfun
$apply$2.apply(ListCompletions.scala:15)
scala.Option.map(Option.scala:145)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1.apply(Li
stCompletions.scala:15)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1.apply(Li
stCompletions.scala:14)
scala.Option.flatMap(Option.scala:170)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1.apply(ListCompletions.sca
la:14)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1.apply(ListCompletions.sca
la:13)
scala.Option.flatMap(Option.scala:170)
com.neowit.apex.actions.ListCompletions.act(ListCompletions.scala:13)
com.neowit.apex.Executor.run(Runner.scala:106)
com.neowit.apex.Executor.execute(Runner.scala:44)
com.neowit.CommandProcessor.processCommand(TcpServer.scala:189)
com.neowit.CommandProcessor$$anonfun$receive$2.applyOrElse(TcpServer.scala:128)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:423)
akka.actor.ActorCell.invoke(ActorCell.scala:397)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:233)
akka.dispatch.Mailbox.run(Mailbox.scala:215)
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatc
her.scala:506)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107
)

Disconnect /127.0.0.1:60696

**Comment by pratsgithub** [comment]
Hi neowit

I have been getting the same issue for past few weeks. However, did not want to bother any of you during the holidays time. Please see below for the exceptions. This log has been generated by version 3.1.5. I also deleted all the files from the src/classes folder and just kept the A_Fake_Class.cls file in that folder. Please let me know if you need any further details.

:!echo " --action=listCompletions --tempFolderPath='/tmp/apex/gvim-deployment' --config='/Users/pratykumar/Documents/workspace-vim/TWG.properties' --projectPath='/Users/pratykumar/Documents/workspace-v
im/TWG' --column=16 --line=6 --currentFilePath='/Users/pratykumar/Documents/workspace-vim/TWG/src/classes/A_Fake_Class.cls' --currentFileContentPath='/var/folders/q5/hsg1sxp536jbdhpqtnpyzjj0wp35w7/T/vr
VjGOz/2A_Fake_Class.cls' --responseFilePath='/Users/pratykumar/Documents/workspace-vim/TWG/.vim-force.com/response_listCompletions' --pollWaitMillis=1000 --maxPollRequests=1000" | nc 127.0.0.1 8888
[ERROR] Executor - java.lang.NullPointerException
[ERROR] Executor - com.neowit.apex.parser.PropertyMember$$anonfun$getModifiers$1.apply(Member.scala:812)
com.neowit.apex.parser.PropertyMember$$anonfun$getModifiers$1.apply(Member.scala:812)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
scala.collection.Iterator$class.foreach(Iterator.scala:727)
scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
scala.collection.AbstractIterable.foreach(Iterable.scala:54)
scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
scala.collection.AbstractTraversable.map(Traversable.scala:105)
com.neowit.apex.parser.PropertyMember$.getModifiers(Member.scala:812)
com.neowit.apex.parser.FieldMember.getModifiers(Member.scala:887)
com.neowit.apex.parser.FieldMember.<init>(Member.scala:890)
com.neowit.apex.parser.TreeListener.enterFieldDeclaration(TreeListener.scala:199)
com.neowit.apex.parser.antlr.ApexcodeParser$FieldDeclarationContext.enterRule(ApexcodeParser.java:1914)
org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:66)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:49)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
com.neowit.apex.parser.SourceScanner$$anonfun$scan$1.apply(SourceScanner.scala:39)
com.neowit.apex.parser.SourceScanner$$anonfun$scan$1.apply(SourceScanner.scala:23)
scala.collection.immutable.List.foreach(List.scala:318)
com.neowit.apex.parser.SourceScanner.scan(SourceScanner.scala:23)
com.neowit.apex.actions.ScanSource.scan(ScanSource.scala:38)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1$$anonfun$apply$2.apply(ListCompletions.scala:24)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1$$anonfun$apply$2.apply(ListCompletions.scala:15)
scala.Option.map(Option.scala:145)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1.apply(ListCompletions.scala:15)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1.apply(ListCompletions.scala:14)
scala.Option.flatMap(Option.scala:170)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1.apply(ListCompletions.scala:14)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1.apply(ListCompletions.scala:13)
scala.Option.flatMap(Option.scala:170)
com.neowit.apex.actions.ListCompletions.act(ListCompletions.scala:13)
com.neowit.apex.Executor.run(Runner.scala:106)
com.neowit.apex.Executor.execute(Runner.scala:44)
com.neowit.CommandProcessor.processCommand(TcpServer.scala:189)
com.neowit.CommandProcessor$$anonfun$receive$2.applyOrElse(TcpServer.scala:128)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:423)
akka.actor.ActorCell.invoke(ActorCell.scala:397)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:233)
akka.dispatch.Mailbox.run(Mailbox.scala:215)
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:506)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

RESULT=FAILURE
ERROR: {"text" : }

// PK

**Comment by pratsgithub** [comment]
Hi neowit

I have been getting the same issue for past few weeks. However, did not want to bother any of you during the holidays time. Please see below for the exceptions. This log has been generated by version 3.1.5. I also deleted all the files from the src/classes folder and just kept the A_Fake_Class.cls file in that folder. Please let me know if you need any further details.

:!echo " --action=listCompletions --tempFolderPath='/tmp/apex/gvim-deployment' --config='/Users/pratykumar/Documents/workspace-vim/TWG.properties' --projectPath='/Users/pratykumar/Documents/workspace-v
im/TWG' --column=16 --line=6 --currentFilePath='/Users/pratykumar/Documents/workspace-vim/TWG/src/classes/A_Fake_Class.cls' --currentFileContentPath='/var/folders/q5/hsg1sxp536jbdhpqtnpyzjj0wp35w7/T/vr
VjGOz/2A_Fake_Class.cls' --responseFilePath='/Users/pratykumar/Documents/workspace-vim/TWG/.vim-force.com/response_listCompletions' --pollWaitMillis=1000 --maxPollRequests=1000" | nc 127.0.0.1 8888
[ERROR] Executor - java.lang.NullPointerException
[ERROR] Executor - com.neowit.apex.parser.PropertyMember$$anonfun$getModifiers$1.apply(Member.scala:812)
com.neowit.apex.parser.PropertyMember$$anonfun$getModifiers$1.apply(Member.scala:812)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
scala.collection.Iterator$class.foreach(Iterator.scala:727)
scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
scala.collection.AbstractIterable.foreach(Iterable.scala:54)
scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
scala.collection.AbstractTraversable.map(Traversable.scala:105)
com.neowit.apex.parser.PropertyMember$.getModifiers(Member.scala:812)
com.neowit.apex.parser.FieldMember.getModifiers(Member.scala:887)
com.neowit.apex.parser.FieldMember.<init>(Member.scala:890)
com.neowit.apex.parser.TreeListener.enterFieldDeclaration(TreeListener.scala:199)
com.neowit.apex.parser.antlr.ApexcodeParser$FieldDeclarationContext.enterRule(ApexcodeParser.java:1914)
org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:66)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:49)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
com.neowit.apex.parser.SourceScanner$$anonfun$scan$1.apply(SourceScanner.scala:39)
com.neowit.apex.parser.SourceScanner$$anonfun$scan$1.apply(SourceScanner.scala:23)
scala.collection.immutable.List.foreach(List.scala:318)
com.neowit.apex.parser.SourceScanner.scan(SourceScanner.scala:23)
com.neowit.apex.actions.ScanSource.scan(ScanSource.scala:38)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1$$anonfun$apply$2.apply(ListCompletions.scala:24)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1$$anonfun$apply$2.apply(ListCompletions.scala:15)
scala.Option.map(Option.scala:145)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1.apply(ListCompletions.scala:15)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1$$anonfun$apply$1.apply(ListCompletions.scala:14)
scala.Option.flatMap(Option.scala:170)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1.apply(ListCompletions.scala:14)
com.neowit.apex.actions.ListCompletions$$anonfun$act$1.apply(ListCompletions.scala:13)
scala.Option.flatMap(Option.scala:170)
com.neowit.apex.actions.ListCompletions.act(ListCompletions.scala:13)
com.neowit.apex.Executor.run(Runner.scala:106)
com.neowit.apex.Executor.execute(Runner.scala:44)
com.neowit.CommandProcessor.processCommand(TcpServer.scala:189)
com.neowit.CommandProcessor$$anonfun$receive$2.applyOrElse(TcpServer.scala:128)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:423)
akka.actor.ActorCell.invoke(ActorCell.scala:397)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:233)
akka.dispatch.Mailbox.run(Mailbox.scala:215)
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:506)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

RESULT=FAILURE
ERROR: {"text" : }

// PK

**Comment by pratsgithub** [comment]
And below is a dump from the temp file that gets created.

$ cat /var/folders/q5/hsg1sxp536jbdhpqtnpyzjj0wp35w7/T/vrVjGOz/2A_Fake_Class.cls
public with sharing class A_Fake_Class {
    public PageReference navToContactPage() {
        PageReference ref = new PageReference('/'+contactId);
        ref.setRedirect(true);
        System.Debug(ref);
        system.     //trying code complete here by pressing ctrl-x,ctrl-o
        return ref;
    }
}

**Comment by pratsgithub** [comment]
Please ignore the previous 2 comments. I had not deleted all the files from my source. After deleting all the files and just retaining the A_Fake_Class.cls, it worked. I also managed to figure out one of the files that is failing to be parsed successfully. Below is the source code of the file that failed to parse.

public class AttachmentsWrapper {
        
       public transient list<AttachmentsWrapperlist> AWrapperL;
       public transient List<String> docIdList {get; set;}
       
       
       public Attachment attach {get;set;}
       // Private Dummy General Object Record
        private General_Object__c dummyGenObj;
        
        public AttachmentsWrapper(){           
        }   
             
        public AttachmentsWrapperlist uploadAttachment(Attachment att){
        
        docIdList = new List<String>();
        
        dummyGenObj = new General_Object__c();
        insert dummyGenObj;
        
        if(att.body != null) {
            att.parentId = dummyGenObj.Id;
            insert att;
            
            docIdList.add(att.id);
            attach = [SELECT id, 
                             name, 
                             description, 
                             CreatedDate, 
                             bodylength 
                             FROM Attachment 
                             WHERE id = :att.id];
            
            String size = '';
            if(1048576 < attach.BodyLength) {
                // Size greater than 1MB
                size = '' + (attach.BodyLength / 1048576) + ' MB';
            }
            else if(1024 < att.BodyLength) {
                // Size greater than 1KB
                size = '' + (attach.BodyLength / 1024) + ' KB';            
            }
            else {
                size = '' + attach.BodyLength + ' bytes';
            }
            
            AttachmentsWrapperlist UploadedDocumentList = new AttachmentsWrapperlist(true, att.name, att.id, size, att.CreatedDate, att.description);
             
            return UploadedDocumentList;
        }
    
        return null;
    }      
    
    public list<attachment> uploadRelatedAttachment(case c, list<AttachmentsWrapperlist> Awl)
    {
            List<String> selectedDocumentId = new List<String>();
            for(AttachmentsWrapperlist aWrapper : Awl) 
            {
                if(aWrapper.isSelected) 
                {
                    selectedDocumentId.add(aWrapper.documentId);
                }
            }
            
            /* Select Documents which are Only Active (Selected) */
              List<Attachment> selectedAttachmentList = new List<Attachment>();
             if(!selectedDocumentId.isEmpty()){
                selectedAttachmentList = [
                                           SELECT 
                                               id,
                                               name,
                                               ContentType,
                                               parentid,
                                               Body,
                                               description 
                                           FROM 
                                               Attachment 
                                           WHERE 
                                               id IN :selectedDocumentId
                                        ];
            }
            
             List<Attachment> attachmentsToInsertList = new List<Attachment>();
              set<id> GenObjIds = new set<id>();
              for(Attachment at : selectedAttachmentList){
                  GenObjIds.add(at.parentid);     
              }
              
            for(Attachment attached : selectedAttachmentList){
                Attachment a = new Attachment();
                a.body = attached.body;
                a.ContentType = attached.ContentType;
                a.Name= attached.Name;
                a.parentid = c.id; //Case Record Id which is been recently created.
                a.description = attached.description;
                attachmentsToInsertList.add(a);                
            }
            
            if(!attachmentsToInsertList.isEmpty()){
                insert attachmentsToInsertList;
                
                list<General_Object__c> GenObj  = [select id from General_Object__c where id IN:GenObjIds];
                delete GenObj;
                return attachmentsToInsertList;
            }
         
        return null;
    }             
}

**Comment by neowit** [comment]
Hi @pratsgithub 

Thanks for the example of the failing file, I will look into this.

By the way - based on the exception in your first message it does not seem that you were running v.0.3.1.5 at that time. If you did then I would expect two differences with the result you got:

1. completion in A_Fake_Class would have been successful 
  - because in tooling-force.com.jar v0.3.1.5 exceptions thrown by parser in one file should not cause completion failure in another (unrelated) class.  

2. In your exception stack trace we would see the name of the offending file right before the stack trace.
FYI - If you did not shut down the server (e.g. killed java process) then even if you replace the .jar file all calls to tooling-force.com.jar "server" will be handled by already running instance.
In the future I recommend to check tooling-force.com.jar version to be sure: `:ApexToolingVersion`

**Comment by neowit** [comment]
@pratsgithub 
try [tooling-force.com.jar v0.3.1.6](/neowit/tooling-force.com/releases/tag/v0.3.1.6)
with that one you shall be able to complete stuff in AttachmentsWrapper class without seeing errors.
Before testing make sure that you are running the correct version with `:ApexToolingVersion` in vim.
If you do encounter errors please open another issue.

**Comment by pratsgithub** [comment]
Thanks Andrey. This version works like a charm. :)
