### ISSUE TITLE
Return an error code when the command fails for whatever reason.

### ISSUE THREAD

**Issue by thomasdziedzic** [neowit/tooling-force.com#7]
I currently have to ```grep RESULT=SUCCESS``` in order to detect whether there was a success using tooling-force.com 0.3.3.3

It would be nice if I could just go off of the return code.

**Comment by neowit** [comment]
Hi Thomas,

For now i have added a very basic return code - non zero means no good.
In the future may add error specific (non zero) exit codes, but for now no such plans.

It is going to be a while before I build a release .jar with this change. Current master version includes some changes which have not been tested yet. I can share current dev build here though. Let me know if you want to test it.

**Comment by thomasdziedzic** [comment]
That was really fast Thanks!

RE: jar, I can wait, I have worked around this issue already with a grep and I would rather use released versions in our production code for now since this isn't a blocker.
